### PR TITLE
Reviewed changes

### PR DESCRIPTION
**Pull request by lhamutserings**

### CODE REVIEW

**Comment by lhamutserings** [comment]
I've rebased my branch and re-added the changes. 
Edit: Sponsor link is still not working, even after changes made to the config file.

**Comment by lhamutserings** [comment]
Sponsor link seems to be working fine after this commit.

**Review by rinchenlama0075 — APPROVED** [review]
LGTM

**Comment by rinchenlama0075** [comment]
@lhamutserings Merged!!! 🥳

**Pull request merged**
